//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveNetwork.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ANDBEntities : DbContext
    {
        public ANDBEntities()
            : base("name=ANDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANEvent> ANEvents { get; set; }
        public virtual DbSet<ANEventImage> ANEventImages { get; set; }
        public virtual DbSet<ANEventInformation> ANEventInformations { get; set; }
        public virtual DbSet<ANEventMember> ANEventMembers { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<RequestToJoin> RequestToJoins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
